max_parallel_processes: 1

source:
  uuid: "FED7-AF89"
  mount_point: "/mnt/tmp"
  path: "backups"
  exclude_patterns: []

destinations:
  - uuid: "ED47-D236"
    mount_point: "/mnt/hdda"
    path: "backups"
    priority: 1
    deletion_policy: "oldest"
    deletion_exclude_patterns: []
